[package]
name = "fosscord-client"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.10.0", features = [] }

[dependencies]
tauri = { version = "2.10.0", features = [] }
